backend:
  name: github
  repo: connecttechnologyteam/devnotes
  branch: main
  publish_mode: simple
  base_url: https://devnotes-oauth.vercel.app
  site_url: https://connecttechnologyteam.github.io/devnotes

# Media storage
# Media storage
media_folder: "public/uploads"
public_folder: "/uploads"

# Collections
collections:
  # Users collection
  - name: "users"
    label: "Users"
    folder: "content/users"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: github, label: "GitHub Login", widget: "string" }
      - { name: name,   label: "Full Name",    widget: "string", required: false }
      - { name: avatar, label: "Avatar",       widget: "image",  required: false }
      - { name: bio,    label: "Bio",          widget: "text",   required: false }
      - { name: role,   label: "Role",         widget: "select", options: ["author","editor","admin"], default: "author" }
  # Posts collection
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - label: Author (slug from users)
        name: author
        widget: relation
        collection: "users"
        value_field: "{{slug}}"
        search_fields: ["name","github"]
        display_fields: ["name","github"]
      - { name: description, label: Summary, widget: text, required: false }
      - { name: tags, label: Tags, widget: list, required: false }
      - { name: featured_image, label: Featured Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }
      - { name: draft, label: Draft, widget: boolean, default: false }

  # Pages collection
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Draft", name: "draft", widget: "boolean", default: false}

