backend:
  name: git-gateway
  branch: duc-develop # change if your default branch is different

media_folder: "public/uploads" # where uploaded files go in your repo
public_folder: "/uploads" # how the site references them

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/users" # e.g., Markdown files live here
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
