publish_mode: editorial_workflow

backend:
  # choose one you actually use
  name: git-gateway # (Netlify Identity + Git Gateway)
  # or
  # name: github
  # repo: your-user/your-repo
  branch: main

collections:
  - name: blog # 👈 this "name" is used in the URL below
    label: Blog
    folder: content/user
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
